CRITICAL - 2023-08-30 09:18:21 --> syntax error, unexpected single-quoted string "created_on", expecting "]"
in APPPATH\Models\TestimonialModel.php on line 13.
 1 SYSTEMPATH\Autoloader\Autoloader.php(291): CodeIgniter\Autoloader\Autoloader->includeFile('E:\\xampp\\htdocs\\app\\Models\\TestimonialModel.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(269): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\TestimonialModel')
 3 APPPATH\Controllers\Home.php(12): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\TestimonialModel')
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-30 09:20:18 --> Undefined variable $testimonials
in APPPATH\Views\includes\testimonials.php on line 33.
 1 APPPATH\Views\includes\testimonials.php(33): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $testimonials', 'E:\\xampp\\htdocs\\app\\Views\\includes\\testimonials.php', 33)
 2 APPPATH\Views\about.php(333): include('E:\\xampp\\htdocs\\app\\Views\\includes\\testimonials.php')
 3 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\app\\Views\\about.php')
 4 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('about', [], true)
 6 APPPATH\Controllers\Home.php(23): view('about')
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->about()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-30 09:21:01 --> Undefined variable $testimonials
in APPPATH\Views\includes\testimonials.php on line 33.
 1 APPPATH\Views\includes\testimonials.php(33): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $testimonials', 'E:\\xampp\\htdocs\\app\\Views\\includes\\testimonials.php', 33)
 2 APPPATH\Views\services.php(518): include('E:\\xampp\\htdocs\\app\\Views\\includes\\testimonials.php')
 3 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\app\\Views\\services.php')
 4 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('services', [], true)
 6 APPPATH\Controllers\Home.php(30): view('services')
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->services()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-30 13:04:48 --> App\Controllers\Contact::contact(): Return value must be of type string, array returned
in APPPATH\Controllers\Contact.php on line 40.
 1 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Contact->contact()
 2 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Contact))
 3 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-30 13:12:52 --> Undefined property: App\Controllers\Contact::$session
in APPPATH\Controllers\Contact.php on line 88.
 1 APPPATH\Controllers\Contact.php(88): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Contact::$session', 'E:\\xampp\\htdocs\\app\\Controllers\\Contact.php', 88)
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Contact->contact()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Contact))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-30 13:14:09 --> App\Controllers\Contact::contact(): Return value must be of type string, CodeIgniter\HTTP\RedirectResponse returned
in APPPATH\Controllers\Contact.php on line 90.
 1 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Contact->contact()
 2 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Contact))
 3 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-30 13:14:48 --> App\Controllers\Contact::contact(): Return value must be of type string, CodeIgniter\HTTP\RedirectResponse returned
in APPPATH\Controllers\Contact.php on line 90.
 1 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Contact->contact()
 2 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Contact))
 3 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-30 13:18:47 --> Cannot use isset() on the result of an expression (you can use "null !== expression" instead)
in APPPATH\Views\contact.php on line 36.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-08-30 18:56:51 --> Undefined array key "message"
in APPPATH\Controllers\Contact.php on line 84.
 1 APPPATH\Controllers\Contact.php(84): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "message"', 'E:\\xampp\\htdocs\\app\\Controllers\\Contact.php', 84)
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Contact->contact()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Contact))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-30 18:57:05 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in E:\xampp\htdocs\system\Email\Email.php:1735
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'E:\\xampp\\htdocs...', 1735)
#1 E:\xampp\htdocs\system\Email\Email.php(1735): mail('sharatkumar2599...', '=?UTF-8?Q?New=2...', 'This is a multi...', 'Date: Wed, 30 A...', '-f sparebook001...')
#2 E:\xampp\htdocs\system\Email\Email.php(1667): CodeIgniter\Email\Email->sendWithMail()
#3 E:\xampp\htdocs\system\Email\Email.php(1565): CodeIgniter\Email\Email->spoolEmail()
#4 E:\xampp\htdocs\app\Controllers\Contact.php(97): CodeIgniter\Email\Email->send()
#5 E:\xampp\htdocs\system\CodeIgniter.php(932): App\Controllers\Contact->contact()
#6 E:\xampp\htdocs\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Contact))
#7 E:\xampp\htdocs\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\xampp\htdocs\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2023-08-30 18:57:05 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2023-08-30 18:57:05 --> 
ERROR - 2023-08-30 18:59:47 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in E:\xampp\htdocs\system\Email\Email.php:1735
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'E:\\xampp\\htdocs...', 1735)
#1 E:\xampp\htdocs\system\Email\Email.php(1735): mail('sharatkumar2599...', '=?UTF-8?Q?New=2...', 'This is a multi...', 'Date: Wed, 30 A...', '-f sparebook001...')
#2 E:\xampp\htdocs\system\Email\Email.php(1667): CodeIgniter\Email\Email->sendWithMail()
#3 E:\xampp\htdocs\system\Email\Email.php(1565): CodeIgniter\Email\Email->spoolEmail()
#4 E:\xampp\htdocs\app\Controllers\Contact.php(97): CodeIgniter\Email\Email->send()
#5 E:\xampp\htdocs\system\CodeIgniter.php(932): App\Controllers\Contact->contact()
#6 E:\xampp\htdocs\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Contact))
#7 E:\xampp\htdocs\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\xampp\htdocs\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2023-08-30 18:59:47 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2023-08-30 18:59:47 --> 
ERROR - 2023-08-30 19:03:25 --> Email: Unable to send email using Sendmail. Your server might not be configured to send mail using this method.
ERROR - 2023-08-30 19:03:25 --> Exit status code: 1
Unable to open a socket to Sendmail. Please check settings.
ERROR - 2023-08-30 19:04:21 --> Email: Unable to send email using Sendmail. Your server might not be configured to send mail using this method.
ERROR - 2023-08-30 19:04:21 --> Exit status code: 1
Unable to open a socket to Sendmail. Please check settings.
ERROR - 2023-08-30 13:48:00 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in E:\xampp\htdocs\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\xampp\htdocs\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'overninja_db', 3306, '', 0)
#1 E:\xampp\htdocs\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\app\Controllers\Home.php(13): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\system\CodeIgniter.php(932): App\Controllers\Home->index()
#8 E:\xampp\htdocs\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\xampp\htdocs\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in E:\xampp\htdocs\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\app\Controllers\Home.php(13): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\system\CodeIgniter.php(932): App\Controllers\Home->index()
#7 E:\xampp\htdocs\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\xampp\htdocs\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-08-30 13:48:00 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `testimonials`
ORDER BY `created_on` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
